# Generated by Django 6.0.7 on 2026-07-15 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cursos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Evaluacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("diagnostico", "Diagnóstico"),
                            ("formativa", "Formativa"),
                            ("sumativa", "Sumativa"),
                            ("final", "Final"),
                        ],
                        default="formativa",
                        max_length=20,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_limite", models.DateTimeField(blank=True, null=True)),
                ("duracion_minutos", models.IntegerField(default=30)),
                ("puntaje_maximo", models.FloatField(default=100)),
                ("publicado", models.BooleanField(default=False)),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluaciones",
                        to="cursos.curso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evaluación",
                "verbose_name_plural": "Evaluaciones",
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="Pregunta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pregunta", models.TextField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("multiple", "Opción Múltiple"),
                            ("verdadero_falso", "Verdadero/Falso"),
                            ("completar", "Completar"),
                            ("abierta", "Pregunta Abierta"),
                        ],
                        default="multiple",
                        max_length=20,
                    ),
                ),
                (
                    "opciones",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Para opción múltiple: ["Opción A", "Opción B", ...]',
                    ),
                ),
                (
                    "respuesta_correcta",
                    models.TextField(
                        help_text='Para múltiple: índice (0,1,2...). Para V/F: "V" o "F"'
                    ),
                ),
                ("puntaje", models.FloatField(default=1.0)),
                ("orden", models.IntegerField(default=0)),
                ("explicacion", models.TextField(blank=True, null=True)),
                (
                    "evaluacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preguntas",
                        to="evaluaciones.evaluacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pregunta",
                "verbose_name_plural": "Preguntas",
                "ordering": ["orden"],
            },
        ),
        migrations.CreateModel(
            name="RespuestaUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("respuesta", models.TextField()),
                ("calificacion", models.FloatField(default=0.0)),
                ("fecha_respuesta", models.DateTimeField(auto_now_add=True)),
                (
                    "pregunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="evaluaciones.pregunta",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respuestas_evaluaciones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Respuesta",
                "verbose_name_plural": "Respuestas",
                "unique_together": {("usuario", "pregunta")},
            },
        ),
        migrations.CreateModel(
            name="ResultadoEvaluacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("puntaje_obtenido", models.FloatField(default=0.0)),
                ("aprobado", models.BooleanField(default=False)),
                ("fecha_inicio", models.DateTimeField(auto_now_add=True)),
                ("fecha_completado", models.DateTimeField(blank=True, null=True)),
                ("intentos", models.IntegerField(default=1)),
                (
                    "evaluacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="evaluaciones.evaluacion",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultados_evaluaciones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Resultado",
                "verbose_name_plural": "Resultados",
                "unique_together": {("usuario", "evaluacion")},
            },
        ),
    ]
