# Generated by Django 6.0.7 on 2026-07-16 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("evaluaciones", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="respuestausuario",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="respuestas_evaluaciones",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="resultadoevaluacion",
            name="evaluacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="evaluaciones.evaluacion",
            ),
        ),
        migrations.AddField(
            model_name="resultadoevaluacion",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resultados_evaluaciones",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="respuestausuario",
            unique_together={("usuario", "pregunta")},
        ),
        migrations.AlterUniqueTogether(
            name="resultadoevaluacion",
            unique_together={("usuario", "evaluacion")},
        ),
    ]
