# Generated by Django 6.0.7 on 2026-07-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActividadUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("curso_iniciado", "Curso Iniciado"),
                            ("curso_completado", "Curso Completado"),
                            ("leccion_completada", "Lección Completada"),
                            ("insignia_obtenida", "Insignia Obtenida"),
                            ("puntos_obtenidos", "Puntos Obtenidos"),
                        ],
                        max_length=30,
                    ),
                ),
                ("descripcion", models.CharField(max_length=500)),
                ("puntos", models.IntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="Certificado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(blank=True, max_length=50, unique=True)),
                ("fecha_emision", models.DateTimeField(auto_now_add=True)),
                ("fecha_completado", models.DateTimeField()),
                ("puntuacion", models.FloatField(default=0.0)),
                ("horas", models.IntegerField(default=0)),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="certificados/"),
                ),
            ],
            options={
                "verbose_name": "Certificado",
                "verbose_name_plural": "Certificados",
                "ordering": ["-fecha_emision"],
            },
        ),
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("principiante", "Principiante"),
                            ("intermedio", "Intermedio"),
                            ("avanzado", "Avanzado"),
                            ("experto", "Experto"),
                        ],
                        default="principiante",
                        max_length=20,
                    ),
                ),
                ("imagen_url", models.URLField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("publicado", models.BooleanField(default=False)),
                ("duracion_horas", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-fecha_creacion"],
            },
        ),
        migrations.CreateModel(
            name="Inscripcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inscripcion", models.DateTimeField(auto_now_add=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("activo", "Activo"),
                            ("completado", "Completado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("progreso", models.IntegerField(default=0)),
                ("fecha_completado", models.DateTimeField(blank=True, null=True)),
                ("calificacion", models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name="Insignia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("bronce", "Bronce"),
                            ("plata", "Plata"),
                            ("oro", "Oro"),
                            ("platino", "Platino"),
                            ("diamante", "Diamante"),
                        ],
                        default="bronce",
                        max_length=20,
                    ),
                ),
                ("icono", models.CharField(default="🏆", max_length=50)),
                ("puntos_requeridos", models.IntegerField(default=0)),
                ("cursos_requeridos", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="InsigniaUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_obtencion", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Leccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("orden", models.IntegerField(default=0)),
                ("video_url", models.URLField(blank=True, null=True)),
                ("duracion_minutos", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["orden"],
            },
        ),
        migrations.CreateModel(
            name="ProgresoLeccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completado", models.BooleanField(default=False)),
                ("fecha_completado", models.DateTimeField(blank=True, null=True)),
                ("tiempo_estudio", models.IntegerField(default=0)),
                ("intentos", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="PuntosUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_puntos", models.IntegerField(default=0)),
                ("racha_dias", models.IntegerField(default=0)),
                ("ultimo_actividad", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
