# Generated by Django 6.0.7 on 2026-07-16 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(blank=True, max_length=50, unique=True)),
                ("fecha_emision", models.DateTimeField(auto_now_add=True)),
                ("fecha_completado", models.DateTimeField()),
                ("puntuacion", models.FloatField(default=0.0)),
                ("horas", models.IntegerField(default=0)),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="certificados/"),
                ),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificados_curso",
                        to="cursos.curso",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificados_curso",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificado",
                "verbose_name_plural": "Certificados",
                "ordering": ["-fecha_emision"],
                "unique_together": {("usuario", "curso")},
            },
        ),
    ]
