# Generated by Django 6.0.7 on 2026-07-16 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("cursos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="actividadusuario",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actividades_gamificacion",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="certificado",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certificados_curso",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="curso",
            name="creador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cursos_creados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="curso",
            name="tecnicas",
            field=models.ManyToManyField(
                blank=True, related_name="cursos", to="core.tecnica"
            ),
        ),
        migrations.AddField(
            model_name="certificado",
            name="curso",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certificados_curso",
                to="cursos.curso",
            ),
        ),
        migrations.AddField(
            model_name="inscripcion",
            name="curso",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cursos.curso"
            ),
        ),
        migrations.AddField(
            model_name="inscripcion",
            name="estudiante",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="insigniausuario",
            name="insignia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cursos.insignia"
            ),
        ),
        migrations.AddField(
            model_name="insigniausuario",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="insignias_usuario",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="leccion",
            name="curso",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lecciones",
                to="cursos.curso",
            ),
        ),
        migrations.AddField(
            model_name="leccion",
            name="tecnica",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.tecnica",
            ),
        ),
        migrations.AddField(
            model_name="progresoleccion",
            name="estudiante",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="progresoleccion",
            name="leccion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="cursos.leccion"
            ),
        ),
        migrations.AddField(
            model_name="puntosusuario",
            name="usuario",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="puntos_usuario",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="certificado",
            unique_together={("usuario", "curso")},
        ),
        migrations.AlterUniqueTogether(
            name="inscripcion",
            unique_together={("estudiante", "curso")},
        ),
        migrations.AlterUniqueTogether(
            name="insigniausuario",
            unique_together={("usuario", "insignia")},
        ),
        migrations.AlterUniqueTogether(
            name="progresoleccion",
            unique_together={("estudiante", "leccion")},
        ),
    ]
