# Generated by Django 6.0.7 on 2026-07-16 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InsigniaAvanzada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField()),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("aprendizaje", "📖 Aprendizaje"),
                            ("logro", "🏅 Logro"),
                            ("desafio", "⚡ Desafío"),
                            ("racha", "🔥 Racha"),
                            ("especial", "✨ Especial"),
                            ("social", "🤝 Social"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("bronce", "🥉 Bronce"),
                            ("plata", "🥈 Plata"),
                            ("oro", "🥇 Oro"),
                            ("platino", "💎 Platino"),
                            ("diamante", "👑 Diamante"),
                        ],
                        default="bronce",
                        max_length=20,
                    ),
                ),
                ("icono", models.CharField(default="🏆", max_length=50)),
                ("puntos_requeridos", models.IntegerField(default=0)),
                ("cursos_requeridos", models.IntegerField(default=0)),
                ("lecciones_requeridas", models.IntegerField(default=0)),
                ("evaluaciones_aprobadas", models.IntegerField(default=0)),
                ("racha_dias", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="NivelUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nivel",
                    models.IntegerField(
                        choices=[
                            (1, "🌱 Novato"),
                            (2, "📚 Aprendiz"),
                            (3, "🔍 Explorador"),
                            (4, "🎓 Conocedor"),
                            (5, "⚡ Experto"),
                            (6, "🏆 Maestro"),
                            (7, "🧠 Sabio"),
                            (8, "👑 Leyenda"),
                            (9, "🌟 Mítico"),
                            (10, "✨ Dios de la Lengua"),
                        ],
                        default=1,
                    ),
                ),
                ("puntos_necesarios", models.IntegerField()),
                ("icono", models.CharField(default="⭐", max_length=50)),
                ("beneficio", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Desafio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("diario", "📅 Desafío Diario"),
                            ("semanal", "📆 Desafío Semanal"),
                            ("mensual", "📊 Desafío Mensual"),
                            ("especial", "🎯 Desafío Especial"),
                        ],
                        max_length=20,
                    ),
                ),
                ("puntos_recompensa", models.IntegerField()),
                ("fecha_inicio", models.DateTimeField()),
                ("fecha_fin", models.DateTimeField()),
                ("activo", models.BooleanField(default=True)),
                (
                    "completado_por",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventoGamificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("puntos", "⭐ Puntos Obtenidos"),
                            ("insignia", "🏅 Insignia Obtenida"),
                            ("nivel", "⬆️ Nivel Alcanzado"),
                            ("racha", "🔥 Racha Lograda"),
                            ("desafio", "⚡ Desafío Completado"),
                            ("logro", "🎯 Logro Alcanzado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descripcion", models.CharField(max_length=500)),
                ("puntos", models.IntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventos_gamificacion",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="RachaUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("racha_actual", models.IntegerField(default=0)),
                ("racha_maxima", models.IntegerField(default=0)),
                ("ultimo_estudio", models.DateTimeField(blank=True, null=True)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="racha",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LogroUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("progreso", models.IntegerField(default=0)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("en_progreso", "🔄 En Progreso"),
                            ("completado", "✅ Completado"),
                            ("reclamado", "🎁 Reclamado"),
                        ],
                        default="en_progreso",
                        max_length=20,
                    ),
                ),
                ("fecha_obtencion", models.DateTimeField(blank=True, null=True)),
                (
                    "insignia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cursos.insigniaavanzada",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logros_usuario",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("usuario", "insignia")},
            },
        ),
    ]
