# Generated by Django 6.0.7 on 2026-07-15 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tecnica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=500)),
                ("contenido", models.TextField(blank=True, null=True)),
                ("categoria", models.CharField(db_index=True, max_length=100)),
                (
                    "subcategoria",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("grado", models.CharField(blank=True, max_length=50, null=True)),
                ("tipo", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "ruta_archivo",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["categoria", "titulo"],
                "indexes": [
                    models.Index(
                        fields=["categoria"], name="core_tecnic_categor_dc49ec_idx"
                    ),
                    models.Index(
                        fields=["titulo"], name="core_tecnic_titulo_7bbac0_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TecnicaJSON",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tecnica_numero", models.IntegerField()),
                ("titulo_tecnica", models.CharField(max_length=200)),
                ("teoria", models.TextField(blank=True, null=True)),
                ("ejemplo", models.TextField(blank=True, null=True)),
                ("ejercicio", models.TextField(blank=True, null=True)),
                ("respuesta", models.TextField(blank=True, null=True)),
                (
                    "tecnica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tecnicas_json",
                        to="core.tecnica",
                    ),
                ),
            ],
            options={
                "ordering": ["tecnica_numero"],
            },
        ),
    ]
